version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: go-dev.Dockerfile
    container_name: go-linebot-crypto
    ports:
      - "4325:4325"
    volumes:
      - "./:/app"
    working_dir: /app
